pool:
  name: self-hosted-agent-ubuntu-16

trigger:
  branches:
    include:
      - master

variables:
  image: flex-sisa-endwment
  tag: $(Build.BuildId)
  containerRegistry: advancedanalyticsacr

steps:
  - script: docker build -f Dockerfile -t $(containerRegistry).azurecr.io/$(image):latest .
    displayName: 'Build Docker image'

  - task: Docker@2
    displayName: Login to ACR
    inputs:
      command: login
      containerRegistry: $(containerRegistry)

  - script: |
      docker push $(containerRegistry).azurecr.io/$(image):latest
    displayName: 'Push Docker image'

  - task: Docker@2
    displayName: Logout of ACR
    inputs:
      command: logout
      containerRegistry: $(containerRegistry)

  - task: CopyFiles@2
    displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
    inputs:
      Contents: |
         **/kubernetes/**
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: deploy'
    inputs:
      ArtifactName: deploy